### ISSUE TITLE
tokenIdBalanceOf not set in sample scripts.

### ISSUE THREAD

**Issue by JAlbertCode** [ChainSafe/game-docs-v2#126]
The tokenIDBalanceOf variable is not set in the [erc1155 balanceOf script](https://docs.gaming.chainsafe.io/current/sample-scripts/#balance-of-2). It throws an error when the user tries to run the script. It will need to be updated to reference the token ID, and we will need to verify that the function is using the right contract address.

**Comment by sneakzttv** [comment]
fixed
