### ISSUE TITLE
Ramp WebGL build section a bit confusing

### ISSUE THREAD

**Issue by JAlbertCode** [ChainSafe/game-docs-v2#132]
The snippets for the paths were a bit confusing to follow and they're slightly different for Macs and PCs. I will update it to make it a bit more clear. This is the section for reference. https://docs.gaming.chainsafe.io/current/ramp#ramp-on-webgl

**Comment by JAlbertCode** [comment]
When the user builds the scene it opens up the file location. They can right click the folder, run terminal, and enter py -m http.server

The open their browser at http://localhost:8000/

**Comment by sneakzttv** [comment]
fixed in #156
