### ISSUE TITLE
Update Docs favicon

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/game-docs-v2#25]
Currently the docs use the standard Docasaurus favicon
![image](https://user-images.githubusercontent.com/12774278/220161830-c961398b-4622-4ad9-8e32-52c3b6083150.png)

**Comment by sneakzttv** [comment]
this just need to be replaced, forwarding on to tim, closing this for now
![image](https://user-images.githubusercontent.com/57473220/220176066-d9a51094-fdb9-4708-8df5-26cea828612e.png)

**Comment by FSM1** [comment]
> this just need to be replaced, forwarding on to tim, closing this for now ![image](https://user-images.githubusercontent.com/57473220/220176066-d9a51094-fdb9-4708-8df5-26cea828612e.png)

No need to close an incomplete issue... It will get closed once a PR resolving the issue gets merged.
