### ISSUE TITLE
Usecase for marketplace

### ISSUE THREAD

**Issue by dhyaniarun1993** [ChainSafe/game-docs-v2#99]
**Description**
Create a tutorial buy showcasing a usecase and how marketplace can be plugged into the game.

**Comment by sneakzttv** [comment]
WIP: https://github.com/ChainSafe/web3.unity/issues/912

**Comment by sneakzttv** [comment]
marketplace core functionality added for 2.6 via modular package, will add a usecase implementation for 3.0

**Comment by sneakzttv** [comment]
complete
